apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: ns-wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

